Yarn Latest Sep 2024 (#59)
# Background
Periodic yarn latest.

Also fixes:
```bash
src/pages/users/[nickname].tsx:9:18 - error TS2307: Cannot find module '@mui/material/Unstable_Grid2' or its corresponding type declarations.

9 import Grid from '@mui/material/Unstable_Grid2'
```

## Checklist Before PR Review
- [x] The following has been handled:
  -  `Draft` is set for this PR
  - `Title` is checked
  - `Background` is filled
  - `Assignee` is set
  - `Labels` are set
  - `development` is linked if related issue exists

## Checklist (Right Before PR Review Request)
- [x] The following has been handled:
  - Final Operation Check is done
  - Make this PR as an open PR

## Checklist (Reviewers)
- [x] Check if there are any other missing TODOs that are not yet listed
- [x] Review Code
- [x] Every item on the checklist has been addressed accordingly
- [x] If `development` is associated to this PR, you must check if every
TODOs are handled